### ISSUE TITLE
Secretservice provider relies on D-Bus

### ISSUE THREAD

**Issue by niothiel** [docker/docker-credential-helpers#105] opened 2018-06-15 20:48 UTC
First, I'm not sure if this the correct place for this issue, but looks like a good starting point. Our scenario is as follows:

* Docker 17.12.1-ce running on Ubuntu 14.04
* A Docker container running Ubuntu 18.04 with `/var/run/docker.sock` volume-mounted onto the host.

Attempt to login to a private Docker registry via: `docker login {private-registry-url} -u foo -p bar`.

The output is as follows:

```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```

I've been able to track the erroneous status exit to the `secretservice` provider, specifically the `docker-credential-secretservice` binary:

```shell
# echo '{"ServerURL": "https://index.docker.io/v1","Username": "foo","Secret": "bar"}' | /usr/bin/docker-credential-secretservice get
Cannot autolaunch D-Bus without X11 $DISPLAY
```

This may be a result of the ubuntu container configuration, as alpine doesn't exhibit this behavior. In any case, this message is not expected as a result of the `docker login` command.

**Comment by chriswue** [comment] 2018-09-10 05:38
Seems to be ultimately the same problem as https://github.com/docker/compose/issues/6023

**Comment by jwalker343** [comment] 2018-09-12 01:27
I was able to work around this issue on 18.04.1 by doing:
```bash
sudo apt-get remove golang-docker-credential-helpers
docker login
<login as normal>
sudo apt-get install docker-compose
```
After I reinstalled compose, `docker login` continued to work as expected.

**Comment by bvisonl** [comment] 2018-09-24 13:28
@jwalker343 Thank you! worked perfectly

**Comment by nyetwurk** [comment] 2018-10-04 14:58
https://github.com/docker/docker-credential-helpers/issues/60#issuecomment-427043185

**Comment by nyetwurk** [comment] 2018-10-04 15:39
https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119

**Comment by nyetwurk** [comment] 2018-10-11 18:47
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823

**Comment by zffocussss** [comment] 2019-01-17 03:44
When using docker login,it shows
Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

**Comment by andreasschulze** [comment] 2019-03-17 09:51
on my Debian (9, but others too) docker is started using /etc/init.d/docker as I don't rely on systemd
/etc/init.d/docker rely on /sbin/start-stop-daemon. And this program do not properly clear environment

If I start a process on a server inside an ssh session from my desktop, 

> /proc/$( pidof dockerd )/environ

 is significant different as if same process will be started at systemboot

So I just restarted my dockerd with
> env -v DISPLAY='' /etc/init.d/dockerd start
read: two sigle quote after DISPLAY=

**Comment by bplein** [comment] 2019-05-02 18:24
Uninstalling docker-compose is a non-starter. Many people rely on it to manage their container instances.

**Comment by nyetwurk** [comment] 2019-05-02 18:28
Well there is zero sign of progress unfortunately. As you can see docker related .deb packaging just isn't on anyone's list of priorities.

**Comment by cherac11** [comment] 2019-05-08 04:47
On CentOS:

yum install -y Xvfb
Xvfb :99 &
export DISPLAY=:99

**Comment by chriswue** [comment] 2019-05-08 18:59
hm, installing a whole bunch of X stuff on a server install seems not exactly the ideal solution but YMMV

**Comment by bplein** [comment] 2019-05-08 19:02
I run my docker container servers with minimal packages installed at the OS level. I've installed stuff before that dragged in X11. Here's what I did (in this order)

- Banged my fist on the table.
- Yelled at the screen
- Uninstalled the package
- Did diffs with old listings to make sure that all of the new packages that got installed were in fact removed, which they sometimes are not.
- Yelled at the screen some more.



> On CentOS:
> 
> yum install -y Xvfb
> Xvfb :99 &
> export DISPLAY=:99
> 
> `dbus-launch --autolaunch` needs an X11 display. You can run it in headless X server (Xvfb).

I run my docker container servers with minimal packages installed at the OS level. I've installed stuff before that dragged in X11. Here's what I did (in this order)

- Banged my fist on the table.
- Yelled at the screen
- Uninstalled the package
- Did diffs with old listings to make sure that all of the new packages that got installed were in fact removed, which they sometimes are not.
- Yelled at the screen some more.

**Comment by nyetwurk** [comment] 2019-05-08 19:31
https://github.com/docker/compose/issues/6023#issuecomment-434041567 illustrates why it is unlikely this will be resolved.

**Comment by dpkirchner** [comment] 2019-07-23 18:03
It looks like you can workaround this bug by renaming `docker-credential-secretservice` out of the way e.g. `mv /usr/bin/docker-credential-secretservice /usr/bin/docker-credential-secretservice.broken`. (Found this at https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119 where they're tracking the same bug).

**Comment by nyetwurk** [comment] 2019-07-23 18:40
It is just sad that the docker community has completely abandoned any sense of responsibility towards downstream package maintainers. They really seem to think you can build an os with only docker containers and pip.

**Comment by akeating** [comment] 2019-08-09 03:57
Just bitten by this on fresh install of Ubuntu 19.04

**Comment by shukriadams** [comment] 2019-08-25 10:26
Hitting this on Raspbian Buster

**Comment by lfuelling** [comment] 2019-09-19 13:24
Why is it necessary to install X on a headless machine just to use `docker login`?

Kind of not KISS... Only S.

**Comment by nyetwurk** [comment] 2019-09-19 16:04
>  install pass and gnupg2
This does not work for me

**Comment by lfuelling** [comment] 2019-09-19 18:19
> > install pass and gnupg2
> 
> This does not work for me

I'm sorry. This is what fixed it for me :c

**Comment by ohcibi** [comment] 2019-09-23 08:56
I can confirm that installing pass and gnupg2 has solved the issue for me on 18.04.

I did https://github.com/docker/docker-credential-helpers/issues/105#issuecomment-420480401 before I installed pass and gnupg2. I was able to `docker login` before `apt install docker-compose` reinstalled the `golang-docker-credential-helpers` package. However after that package got reinstalled `docker login` failed to work as before.

I'm unsure if uninstalling and reinstalling is necessary for the `pass` and `gnupg2` workaround to work.

**Comment by lfuelling** [comment] 2019-09-23 09:32
@ohcibi I read somewhere that you should not use the docker-compose version in apt. I'm using the `curl | bash` version of docker-compose and it works without problems with pass and gnupg2.

**Comment by ohcibi** [comment] 2019-09-23 09:40
@lfuelling i see. But still the issue with the ubuntu package can be solved by installing pass and gnupg2 but of course this is not in scope of this issue as its an ubuntu issue.

**Comment by nyetwurk** [comment] 2019-09-23 15:38
Again, it is inexcusable that the upstream maintainer for docker-compose and the package maintainers for docker-compose aren't working together.

**Comment by doublehell** [comment] 2019-10-23 22:42
OS: ubuntu 18.04 LTS

I have the same problem for "no basic auth credentials"
and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

but it's solved by
`sudo apt install gnupg2 pass`
without removing the docker-compose.

**Comment by rk-p2p** [comment] 2019-11-04 09:51
OS: Ubuntu 18.04.3 LTS
Same problem.
https://github.com/docker/docker-credential-helpers/issues/105#issuecomment-533128766 solved my issue!

**Comment by kkalisz** [comment] 2019-11-17 11:27
> OS: ubuntu 18.04 LTS
> 
> I have the same problem for "no basic auth credentials"
> and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> 
> but it's solved by
> `sudo apt install gnupg2 pass`
> without removing the docker-compose.

Yes, I can confirm that works on ubuntu 18.04 LTS

**Comment by thaJeztah** [comment] 2019-12-04 10:21
Let me close this issue; the `secretservice` password store (and thus credential helper) cannot be used in a headless setup; using the `pass` store and credential helper instead should be the correct approach for these situations

**Closed by thaJeztah** 2019-12-04 10:21 UTC

**Comment by nyetwurk** [comment] 2019-12-04 16:49
Please contact the downstream package maintainers for both ubuntu and debian at least and attempt to work with them. This disconnect is inexcusable, IMO.

**Comment by thaJeztah** [comment] 2019-12-04 22:26
I don't expect this to be possible as secret service was fully designed for interactive sessions; see https://specifications.freedesktop.org/secret-service/latest/

**Comment by lfuelling** [comment] 2019-12-05 10:24
If the only thing necessary is to install `gnupg2` and `pass`, all the maintainers need to do is list those packages as dependencies. 

This would prevent a lot of pain.

**Comment by thaJeztah** [comment] 2019-12-05 11:44
Best to report that with the Ubuntu package maintainers, who package the [`golang-docker-credential-helpers`](https://packages.ubuntu.com/disco/golang-docker-credential-helpers) package (it's not currently included in docker's packages)

**Comment by SuperSandro2000** [comment] 2019-12-05 13:59
@thaJeztah

there are bug reports ignored for a longer time:

> [bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119](https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119)

https://bugs.launchpad.net/ubuntu/+source/golang-github-docker-docker-credential-helpers/+bug/1794307

> [bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822)
> [bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823)

Also the source of the package is Debian: https://salsa.debian.org/go-team/packages/golang-github-docker-docker-credential-helpers

**Comment by nyetwurk** [comment] 2019-12-05 16:42
This is why software devs ideally should contribute their own packaging information with their software in the form of a `debian/` directory, for example. It is unfair to expect downstream distros to do 100% of the work for every single piece of software.

**Comment by ohcibi** [comment] 2019-12-09 09:03
@nyetwurk I as a software developer disagree. Platform specific stuff shouldn't be in the repository at all. What about `gentoo/`, what about `ubuntu/`, what about `elementary/`, what about `arch/`, what about `alpine/`, etc.....? Theres just too many distributions and even more package managers out there, so it is rather unfair to expect such a thing from every single software developer.

**Comment by lfuelling** [comment] 2019-12-09 10:01
ubuntu, elementary, etc all use the debian packaging format.

imo, if you deliver to a specific package manager, you should also add the specific files to the repo.

**Comment by ohcibi** [comment] 2019-12-09 10:07
They use the same packaging format but they might still require distro specific files. But you are not even getting the point. People are not forced to use a deb based package manager on debian based distros. In fact I listed three examples that do not use apt by default and only two that do so and you short circuited it by just appending "etc." to the two examples that use apt 😉 

Also a software developer is not at all "delivering to a specific manager". We are "releasing software"  and sometimes we even "maintain" packages for certain package managers. Those package managers are not necessarily apt and we don't necessarily maintain all packages for all types of package managers.

**Comment by luans** [comment] 2019-12-09 18:18
> OS: ubuntu 18.04 LTS
> 
> I have the same problem for "no basic auth credentials"
> and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> 
> but it's solved by
> `sudo apt install gnupg2 pass`
> without removing the docker-compose.

This answer saved my time. Ubuntu server 18.04. Thank you.

**Comment by lfuelling** [comment] 2019-12-09 20:48
> They use the same packaging format but they might still require distro specific files. 

So where is the problem adding those when "developing" *and* "maintaining" the software?

> But you are not even getting the point. People are not forced to use a deb based package manager on debian based distros. In fact I listed three examples that do not use apt by default and only two that do so and you short circuited it by just appending "etc." to the two examples that use apt wink

The `etc.` meant other Debian based distros. Speaking of getting the point...  

> Also a software developer is not at all "delivering to a specific package manager". We are "releasing software" and sometimes we even "maintain" packages for certain package managers. 

Thanks for explaining the software development glossary to me again, what would the  world be without people like you...

> Those package managers are not necessarily apt and we don't necessarily maintain all packages for all types of package managers.

Imo the developers should try to merge the files required for packaging into the project as soon as a package for a specific distro gets known to avoid fragmentation.

---------

> Theres just too many distributions and even more package managers out there, so it is rather unfair to expect such a thing from every single software developer.

Good thing this project is on GitHub where multiple people (ideally the package maintainers) can contribute stuff.

**Comment by ohcibi** [comment] 2019-12-10 07:37
> The etc. meant other Debian based distros. Speaking of getting the point...

There is **not only** debian out there. Which was precisely the point you dont want to get. I'm out.

**Comment by lfuelling** [comment] 2019-12-10 15:53
imo that point is irrelevant. I'm sure *as a software developer* you know what you're doing.

**Comment by nyetwurk** [comment] 2019-12-17 02:02
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822#35

Please read this carefully.

**Comment by michaeljs1990** [comment] 2020-02-11 17:50
> It looks like you can workaround this bug by renaming `docker-credential-secretservice` out of the way e.g. `mv /usr/bin/docker-credential-secretservice /usr/bin/docker-credential-secretservice.broken`. (Found this at https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119 where they're tracking the same bug).

I like it.

**Comment by smac89** [comment] 2020-03-29 06:47
On Arch linux, I got around this issue by installing [`dbus-x11`](https://aur.archlinux.org/packages/dbus-x11/).

After restarting my PC, I tried once again with:
```
# docker login registry.gitlab.com
```
After entering my credentials, I ran the command again and this time:
```
➜ sudo docker login registry.gitlab.com                                         
Authenticating with existing credentials...
Login Succeeded
```

**Comment by ShineSmile** [comment] 2021-02-02 07:22
> OS: ubuntu 18.04 LTS
> 
> I have the same problem for "no basic auth credentials"
> and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> 
> but it's solved by
> `sudo apt install gnupg2 pass`
> without removing the docker-compose.

this solve my promblem. Thanks!

**Comment by shukriadams** [comment] 2021-04-30 19:40
> OS: ubuntu 18.04 LTS
> 
> I have the same problem for "no basic auth credentials"
> and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> 
> but it's solved by
> `sudo apt install gnupg2 pass`
> without removing the docker-compose.

confirmed working on Raspbian!

**Comment by silent0clown** [comment] 2023-06-29 12:56
I have same problem for "error getting credentials - err: exit status 1,out: The connection is closesd" on Ubuntu 18.04 server ，Solutions is sudo apt install gnupg2 pass

> > OS: ubuntu 18.04 LTS
> > I have the same problem for "no basic auth credentials"
> > and out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
> > but it's solved by
> > `sudo apt install gnupg2 pass`
> > without removing the docker-compose.
> 
> confirmed working on Raspbian!

I have same problem and have slove it by your solution
