### ISSUE TITLE
Power binaries as part of releases

### ISSUE THREAD

**Issue by ghatwala** [docker/docker-credential-helpers#165] opened 2019-10-04 09:57 UTC
Hi all/ @guillaumerose ,

1) Is there any plan to add - "power/ppc64le" binaries as part of future releases of this repo ?
2) Travis jobs are enabled for power builds - https://github.com/docker/docker-credential-helpers/pull/160 . Any plans to ship binaries via this /other(jenkins) mechanism ?

**Comment by lsmcfadden** [comment] 2019-11-15 15:36
Hi @ghatwala @guillaumerose, any update or forward progress?

**Comment by ghatwala** [comment] 2019-11-15 15:41
Probably @guillaumerose  would be best person to update on this / relay this to someone who matters.

**Comment by thaJeztah** [comment] 2019-12-04 09:47
Looks like a duplicate of https://github.com/docker/docker-credential-helpers/issues/144

**Closed by thaJeztah** 2019-12-04 09:47 UTC
