### ISSUE TITLE
docker-credential-pass password containing extra newline makes everything fail

### ISSUE THREAD

**Issue by nilehmann** [docker/docker-credential-helpers#111] opened 2018-06-25 16:34 UTC
In this line https://github.com/docker/docker-credential-helpers/blob/master/pass/pass_linux.go#L41 the variable `stored` contains `"pass is initialized\n"` which makes `stored == password` false. Adding a new line at the end of `password` fixes the problem for me.

**Comment by nilehmann** [comment] 2018-06-25 16:47
Actually, everything fails because of the extra newline. Changing this line https://github.com/docker/docker-credential-helpers/blob/master/pass/pass_linux.go#L95 by `return strings.Trim(string(result), "\n"), nil` made things work for me. Not sure what should be the proper fix.

I'm using `pass v1.7.2`

**Comment by teohhanhui** [comment] 2018-07-02 14:59
Duplicate of #107?

**Comment by nilehmann** [comment] 2018-07-02 15:21
@teohhanhui, yes, same issue

**Comment by vdemeester** [comment] 2018-07-02 15:23
Then it is closeable :angel:

**Closed by vdemeester** 2018-07-02 15:23 UTC
