### ISSUE TITLE
Error on Docker Pull

### ISSUE THREAD

**Issue by shuntera** [docker/docker-credential-helpers#266] opened 2023-04-28 16:36 UTC
When I attempt the command 'docker pull significantgravitas/auto-gpt' I get the following error:

Using default tag: latest
Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

**Comment by shuntera** [comment] 2023-04-28 16:40
OK, seems to be because there is no :latest tag on the image, you have to specify the 0.2.2 tag (only one there right now). Would recommend applying the latest tag to that image.

**Comment by thaJeztah** [comment] 2023-04-28 17:07
Yes, if there's no `:latest` tag for the image, then it's needed to specify a tag to use.

Note that that image is maintained by a personal account (so it's not an official image, but "someone" created that image); so always be careful if you trust that image. You could try to find contact information for that user and ask them to consider adding a `:latest` tag; https://hub.docker.com/r/significantgravitas/auto-gpt


I'll close this ticket because this is not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2023-04-28 17:07 UTC
